name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0, v1.0.1, etc.

env:
  APP_NAME: "Github Actions Sandbox"
  SCHEME_NAME: "Github Actions Sandbox"
  XCODE_PROJECT: "Github Actions Sandbox.xcodeproj" # or .xcworkspace if you have one

jobs:
  build-and-release:
    runs-on: macos-14 # Use latest macOS runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for versioning
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Install Sparkle CLI tools
        run: |
          # Download Sparkle release with CLI tools
          curl -L -o sparkle.tar.xz https://github.com/sparkle-project/Sparkle/releases/download/2.8.1/Sparkle-2.8.1.tar.xz
          tar -xf sparkle.tar.xz
          # Make tools accessible
          chmod +x sparkle/bin/generate_appcast
          chmod +x sparkle/bin/sign_update
          echo "$PWD/sparkle/bin" >> $GITHUB_PATH
      
      - name: Import Code Signing Certificates
        env:
          CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          
          # Import certificate
          echo "$CERTIFICATE_P12" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          
          rm certificate.p12
      
      - name: Build app
        run: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -archivePath "$PWD/build/$APP_NAME.xcarchive" \
            archive \
            CODE_SIGN_IDENTITY="Developer ID Application" \
            OTHER_CODE_SIGN_FLAGS="--timestamp"
      
      - name: Export app
        run: |
          # Create export options
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>developer-id</string>
            <key>teamID</key>
            <string>${{ secrets.TEAM_ID }}</string>
          </dict>
          </plist>
          EOF
          
          xcodebuild \
            -exportArchive \
            -archivePath "$PWD/build/$APP_NAME.xcarchive" \
            -exportPath "$PWD/build" \
            -exportOptionsPlist exportOptions.plist
      
      - name: Notarize app
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          # Create a zip for notarization
          cd build
          ditto -c -k --keepParent "$APP_NAME.app" "$APP_NAME-notarize.zip"
          
          # Submit for notarization
          xcrun notarytool submit "$APP_NAME-notarize.zip" \
            --apple-id "$APPLE_ID" \
            --password "$APPLE_ID_PASSWORD" \
            --team-id "$TEAM_ID" \
            --wait
          
          # Staple the notarization ticket
          xcrun stapler staple "$APP_NAME.app"
      
      - name: Create distribution package
        run: |
          cd build
          # Create final distributable zip
          ditto -c -k --keepParent "$APP_NAME.app" "$APP_NAME-${{ steps.version.outputs.version }}.zip"
      
      - name: Sign update package
        env:
          SPARKLE_PRIVATE_KEY: ${{ secrets.SPARKLE_PRIVATE_KEY }}
        run: |
          cd build
          # Sign the update with Sparkle's private key
          SIGNATURE=$(echo "$SPARKLE_PRIVATE_KEY" | sign_update "$APP_NAME-${{ steps.version.outputs.version }}.zip")
          echo "SPARKLE_SIGNATURE=$SIGNATURE" >> $GITHUB_ENV
          FILE_SIZE=$(stat -f%z "$APP_NAME-${{ steps.version.outputs.version }}.zip")
          echo "FILE_SIZE=$FILE_SIZE" >> $GITHUB_ENV
      
      - name: Generate appcast
        run: |
          # If you have existing appcast.xml, you can generate it automatically
          # For now, we'll create release notes
          cd build
          generate_appcast --download-url-prefix "https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.tag }}/" .
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/${{ env.APP_NAME }}-${{ steps.version.outputs.version }}.zip
          body: |
            ## What's New
            
            Version ${{ steps.version.outputs.version }}
            
            ### Sparkle Update Information
            ```
            Signature: ${{ env.SPARKLE_SIGNATURE }}
            File Size: ${{ env.FILE_SIZE }} bytes
            ```
            
            Add these to your appcast.xml:
            ```xml
            <item>
                <title>Version ${{ steps.version.outputs.version }}</title>
                <sparkle:version>${{ github.run_number }}</sparkle:version>
                <sparkle:shortVersionString>${{ steps.version.outputs.version }}</sparkle:shortVersionString>
                <pubDate>$(date -R)</pubDate>
                <sparkle:minimumSystemVersion>13.0</sparkle:minimumSystemVersion>
                <enclosure 
                    url="https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.tag }}/${{ env.APP_NAME }}-${{ steps.version.outputs.version }}.zip"
                    sparkle:edSignature="${{ env.SPARKLE_SIGNATURE }}"
                    length="${{ env.FILE_SIZE }}"
                    type="application/octet-stream" />
            </item>
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Cleanup keychain
        if: always()
        run: |
          security delete-keychain build.keychain || true
